project_id = "rtuxaekhfwvpwmvmdaul"

[functions.text-to-speech]
verify_jwt = true

[functions.daily-article-selection]
verify_jwt = true

[functions.tts-stream]
verify_jwt = true

[functions.translate]
verify_jwt = true

[functions.rss-feed]
verify_jwt = true

[functions.explain-article]
verify_jwt = true

[functions.fetch-news]
verify_jwt = true

[functions.dictionary-lookup]
verify_jwt = true